import { Language } from './types';

export const translations = {
  en: {
    appTitle: "Bubble",
    appTitleSuffix: "Detector",
    dataInfo: "Data: Simulated Live • AI: Gemini 2.5 Flash",
    lastUpdated: "Updated",
    riskScoreTitle: "Current Bubble Risk Score",
    riskScoreDesc: "Composite score based on weighted average of key valuation metrics.",
    keyIndicators: "Key Valuation Indicators",
    disclaimerTitle: "Disclaimer:",
    disclaimerText: "This application is for educational and demonstration purposes only. The data displayed is simulated. The AI analysis is generated by a language model and should not be taken as financial advice. Always conduct your own research before investing.",
    aiTitle: "AI Market Analyst",
    analyzeBtn: "Generate Analysis",
    analyzingBtn: "Analyzing...",
    refreshBtn: "Refresh Analysis",
    clickToAnalyze: "Click \"Generate Analysis\" to get a real-time assessment from Gemini 2.5.",
    serviceError: "Service Error",
    serviceErrorText: "Unable to reach the analyst service at this moment. Please try again later.",
    apiMissing: "Analysis Unavailable",
    apiMissingText: "Please provide a valid API Key to receive AI-powered market analysis.",
    yearsAgo: "20 Years Ago",
    today: "Today",
    status: {
      'Undervalued': 'Undervalued',
      'Fair': 'Fair Value',
      'Overvalued': 'Overvalued',
      'Extreme Bubble': 'Extreme Bubble'
    },
    metrics: {
      buffett: {
        name: "Buffett Indicator",
        desc: "Ratio of Total US Stock Market Capitalization to US GDP.",
        benchmarkLabel: "Dotcom Peak (2000)"
      },
      shiller: {
        name: "Shiller P/E Ratio",
        desc: "Price-to-Earnings ratio based on average inflation-adjusted earnings from the previous 10 years.",
        benchmarkLabel: "Dotcom Peak (2000)"
      },
      yield: {
        name: "S&P 500 Dividend Yield",
        desc: "The dividend return on investment for the S&P 500. Lower values often indicate higher valuations.",
        benchmarkLabel: "Dotcom Low (2000)"
      },
      margin: {
        name: "Margin Debt Growth",
        desc: "Year-over-year growth in margin debt. High leverage often precedes corrections.",
        benchmarkLabel: "Danger Zone (>20%)"
      },
      fear_greed: {
        name: "Fear & Greed Index",
        desc: "A compilation of 7 indicators measuring market sentiment.",
        benchmarkLabel: "Neutral (50)"
      },
      ndx_deviation: {
        name: "Nasdaq 100 Deviation",
        desc: "Percentage deviation of the Nasdaq 100 index from its 200-day moving average. High deviation suggests overextension.",
        benchmarkLabel: "Dotcom Peak Deviation"
      },
      put_call: {
        name: "Put/Call Ratio",
        desc: "Ratio of put options to call options volume. Low values indicate extreme greed (bubble risk), high values indicate fear.",
        benchmarkLabel: "Historical Avg"
      },
      ipo_heat: {
        name: "IPO Market Activity",
        desc: "Monthly count of new listings and speculative fervor. A hot IPO market often marks market peaks.",
        benchmarkLabel: "Market Cycle Peak"
      }
    }
  },
  zh: {
    appTitle: "美股泡沫",
    appTitleSuffix: "探测器",
    dataInfo: "数据: 模拟实时 • AI: Gemini 2.5 Flash",
    lastUpdated: "数据更新于",
    riskScoreTitle: "当前市场泡沫评分",
    riskScoreDesc: "基于关键估值指标加权平均计算的综合评分。",
    keyIndicators: "关键估值指标",
    disclaimerTitle: "免责声明：",
    disclaimerText: "本应用仅供教育和演示目的。显示的数据均为模拟数据。AI分析由语言模型生成，不应被视为财务建议。投资前请务必自行研究。",
    aiTitle: "AI 市场分析师",
    analyzeBtn: "生成分析",
    analyzingBtn: "分析中...",
    refreshBtn: "刷新分析",
    clickToAnalyze: "点击“生成分析”以获取 Gemini 2.5 的实时评估。",
    serviceError: "服务错误",
    serviceErrorText: "暂时无法连接分析服务，请稍后再试。",
    apiMissing: "分析不可用",
    apiMissingText: "请提供有效的 API Key 以获取 AI 市场分析。",
    yearsAgo: "20年前",
    today: "今天",
    status: {
      'Undervalued': '低估',
      'Fair': '合理估值',
      'Overvalued': '高估',
      'Extreme Bubble': '极度泡沫'
    },
    metrics: {
      buffett: {
        name: "巴菲特指标 (Buffett Indicator)",
        desc: "美股总市值与美国 GDP 的比率。衡量整体市场估值的宏观指标。",
        benchmarkLabel: "2000年互联网泡沫峰值"
      },
      shiller: {
        name: "席勒市盈率 (Shiller P/E)",
        desc: "基于过去 10 年平均通胀调整后收益的市盈率 (CAPE)。",
        benchmarkLabel: "2000年互联网泡沫峰值"
      },
      yield: {
        name: "标普500 股息率",
        desc: "标普500指数的股息回报率。数值越低通常意味着估值越高。",
        benchmarkLabel: "2000年低点"
      },
      margin: {
        name: "融资余额增长 (Margin Debt)",
        desc: "融资债务的同比增长率。高杠杆率通常是市场调整的前兆。",
        benchmarkLabel: "危险区域 (>20%)"
      },
      fear_greed: {
        name: "恐惧与贪婪指数",
        desc: "综合 7 种衡量市场情绪的指标。极端贪婪通常意味着风险升高。",
        benchmarkLabel: "中性水平 (50)"
      },
      ndx_deviation: {
        name: "纳斯达克100 偏离度",
        desc: "纳斯达克100指数与其200日移动平均线的偏离百分比。偏离度过高通常暗示价格过热。",
        benchmarkLabel: "2000年偏离峰值"
      },
      put_call: {
        name: "Put/Call 比率",
        desc: "看跌期权与看涨期权交易量的比率。数值极低表示市场极度贪婪（泡沫风险），数值高表示恐惧。",
        benchmarkLabel: "历史平均水平"
      },
      ipo_heat: {
        name: "IPO 市场热度",
        desc: "月度IPO数量及市场狂热程度。IPO市场过热（数量激增、首日暴涨）通常是牛市顶部的特征。",
        benchmarkLabel: "市场周期峰值"
      }
    }
  }
};